"""
This type stub file was generated by pyright.
"""

import os
from . import version
from .depends import depends
from .parameterized import CRITICAL, DEBUG, ERROR, INFO, ParamOverrides, Parameter, Parameterized, ParameterizedFunction, Skip, String, Undefined, VERBOSE, WARNING, batch_watch, discard_events, edit_constant, get_logger, logging_level, output, script_repr, shared_parameters
from .parameters import Action, Array, Boolean, Bytes, CalendarDate, CalendarDateRange, Callable, ClassSelector, Color, Composite, DataFrame, Date, DateRange, Dict, Dynamic, Event, FileSelector, Filename, Foldername, HookList, Infinity, Integer, List, ListProxy, ListSelector, Magnitude, MultiFileSelector, Number, NumericTuple, ObjectSelector, Path, Range, Selector, SelectorBase, Series, Time, Tuple, XYCoordinates, get_soft_bounds, guess_bounds, guess_param_types, normalize_path, param_union, parameterized_class, resolve_path
from .reactive import bind, rx
from ._utils import _is_number, abbreviate_paths, as_unicode, concrete_descendents, descendents, exceptions_summarized, hashable, is_ordered_dict, named_objs, produce_value
from setuptools_scm import get_version

if os.path.exists(os.path.join(os.path.dirname(__file__), "..", ".git")):
    __version__ = ...
else:
    ...
main = ...
random_seed = ...
__all__ = ('Action', 'Array', 'Boolean', 'Bytes', 'CRITICAL', 'CalendarDate', 'CalendarDateRange', 'Callable', 'ClassSelector', 'Color', 'Composite', 'DEBUG', 'DataFrame', 'Date', 'DateRange', 'Dict', 'Dynamic', 'ERROR', 'Event', 'FileSelector', 'Filename', 'Foldername', 'HookList', 'INFO', 'Infinity', 'Integer', 'List', 'ListProxy', 'ListSelector', 'Magnitude', 'MultiFileSelector', 'Number', 'NumericTuple', 'ObjectSelector', 'ParamOverrides', 'Parameter', 'Parameterized', 'ParameterizedFunction', 'Path', 'Range', 'Selector', 'SelectorBase', 'Series', 'Skip', 'String', 'Time', 'Tuple', 'Undefined', 'VERBOSE', 'WARNING', 'XYCoordinates', '__version__', '_is_number', 'abbreviate_paths', 'as_unicode', 'batch_watch', 'bind', 'concrete_descendents', 'depends', 'descendents', 'discard_events', 'edit_constant', 'exceptions_summarized', 'get_logger', 'get_soft_bounds', 'guess_bounds', 'guess_param_types', 'hashable', 'is_ordered_dict', 'logging_level', 'main', 'named_objs', 'normalize_path', 'output', 'param_union', 'parameterized_class', 'produce_value', 'random_seed', 'resolve_path', 'rx', 'script_repr', 'serializer', 'shared_parameters', 'version')
