"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from typing import Callable, TYPE_CHECKING, TypeVar
from typing_extensions import Concatenate, ParamSpec

if TYPE_CHECKING:
    P = ParamSpec("P")
    R = TypeVar("R")
    CallableT = TypeVar("CallableT", bound=Callable)
DEFAULT_SIGNATURE = ...
MUTABLE_TYPES = ...
class ParamWarning(Warning):
    """Base Param Warning"""
    ...


class ParamPendingDeprecationWarning(ParamWarning, PendingDeprecationWarning):
    """
    Param PendingDeprecationWarning

    This warning type is useful when the warning is not meant to be displayed
    to REPL/notebooks users, as DeprecationWarning are displayed when triggered
    by code in __main__ (__name__ == '__main__' in a REPL).
    """
    ...


class ParamDeprecationWarning(ParamWarning, DeprecationWarning):
    """
    Param DeprecationWarning

    Ignored by default except when triggered by code in __main__
    """
    ...


class ParamFutureWarning(ParamWarning, FutureWarning):
    """
    Param FutureWarning

    Always displayed.
    """
    ...


class Skip(Exception):
    """Exception that allows skipping an update when resolving a reference."""
    ...


def full_groupby(l, key=...): # -> dict_items[Any, list[Any]]:
    """Groupby implementation which does not require a prior sort"""
    ...

def iscoroutinefunction(function): # -> bool:
    """Whether the function is an asynchronous generator or a coroutine."""
    ...

def flatten(line): # -> Generator[Any, Any, None]:
    """
    Flatten an arbitrarily nested sequence.

    Inspired by: pd.core.common.flatten

    Parameters
    ----------
    line : sequence
        The sequence to flatten

    Notes
    -----
    This only flattens list, tuple, and dict sequences.

    Returns
    -------
    flattened : generator

    """
    ...

def accept_arguments(f: Callable[Concatenate[CallableT, P], R]) -> Callable[P, Callable[[CallableT], R]]:
    """Decorator for decorators that accept arguments"""
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def produce_value(value_obj): # -> object:
    """
    A helper function that produces an actual parameter from a stored
    object: if the object is callable, call it, otherwise return the
    object.

    .. deprecated:: 2.0.0
    """
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def as_unicode(obj): # -> str:
    """
    Safely casts any object to unicode including regular string
    (i.e. bytes) types in python 2.

    .. deprecated:: 2.0.0
    """
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def is_ordered_dict(d): # -> bool:
    """
    Predicate checking for ordered dictionaries. OrderedDict is always
    ordered, and vanilla Python dictionaries are ordered for Python 3.6+

    .. deprecated:: 2.0.0
    """
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def hashable(x): # -> tuple[Any, ...] | tuple[tuple[Any, Any], ...]:
    """
    Return a hashable version of the given object x, with lists and
    dictionaries converted to tuples.  Allows mutable objects to be
    used as a lookup key in cases where the object has not actually
    been mutated. Lookup will fail (appropriately) in cases where some
    part of the object has changed.  Does not (currently) recursively
    replace mutable subobjects.

    .. deprecated:: 2.0.0
    """
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def named_objs(objlist, namesdict=...): # -> OrderedDict[Any, Any]:
    """
    Given a list of objects, returns a dictionary mapping from
    string name for the object to the object itself. Accepts
    an optional name,obj dictionary, which will override any other
    name if that item is present in the dictionary.

    .. deprecated:: 2.0.0
    """
    ...

def descendents(class_): # -> list[Any]:
    """
    Return a list of the class hierarchy below (and including) the given class.

    The list is ordered from least- to most-specific.  Can be useful for
    printing the contents of an entire class hierarchy.
    """
    ...

def concrete_descendents(parentclass): # -> dict[Any, Any]:
    """
    Return a dictionary containing all subclasses of the specified
    parentclass, including the parentclass.  Only classes that are
    defined in scripts that have been run or modules that have been
    imported are included, so the caller will usually first do ``from
    package import *``.

    Only non-abstract classes will be included.
    """
    ...

@_deprecated(warning_cat=ParamFutureWarning)
def abbreviate_paths(pathspec, named_paths): # -> OrderedDict[Any, Any]:
    """
    Given a dict of (pathname,path) pairs, removes any prefix shared by all pathnames.
    Helps keep menu items short yet unambiguous.

    .. deprecated:: 2.0.0
    """
    ...

@contextmanager
def exceptions_summarized(): # -> Generator[None, Any, None]:
    """
    Useful utility for writing docs that need to show expected errors.
    Shows exception only, concisely, without a traceback.
    """
    ...

_running_tasks = ...
def async_executor(func): # -> None:
    ...

class _GeneratorIsMeta(type):
    def __instancecheck__(cls, inst): # -> bool:
        ...
    
    def __subclasscheck__(cls, sub): # -> bool:
        ...
    
    def __iter__(cls): # -> Generator[Any, Any, None]:
        ...
    


class _GeneratorIs(metaclass=_GeneratorIsMeta):
    @classmethod
    def __iter__(cls): # -> Generator[Any, Any, None]:
        ...
    


def gen_types(gen_func): # -> Any:
    """
    Decorator which takes a generator function which yields difference types
    make it so it can be called with isinstance and issubclass.
    """
    ...

