"""
This type stub file was generated by pyright.
"""

from typing import Callable, Protocol, TYPE_CHECKING, TypeVar, TypedDict, overload
from .parameterized import Parameter
from ._utils import accept_arguments

if TYPE_CHECKING:
    CallableT = TypeVar("CallableT", bound=Callable)
    Dependency = Parameter | str
    class DependencyInfo(TypedDict):
        dependencies: tuple[Dependency, ...]
        kw: dict[str, Dependency]
        watch: bool
        on_init: bool
        ...
    
    
    class DependsFunc(Protocol[CallableT]):
        _dinfo: DependencyInfo
        __call__: CallableT
        ...
    
    
@overload
def depends(*dependencies: str, watch: bool = ..., on_init: bool = ...) -> Callable[[CallableT], DependsFunc[CallableT]]:
    ...

@overload
def depends(*dependencies: Parameter, watch: bool = ..., on_init: bool = ..., **kw: Parameter) -> Callable[[CallableT], DependsFunc[CallableT]]:
    ...

@accept_arguments
def depends(func: CallableT, /, *dependencies: Dependency, watch: bool = ..., on_init: bool = ..., **kw: Parameter) -> Callable[[CallableT], DependsFunc[CallableT]]:
    """
    Annotates a function or Parameterized method to express its dependencies.

    The specified dependencies can be either be Parameter instances or if a
    method is supplied they can be defined as strings referring to Parameters
    of the class, or Parameters of subobjects (Parameterized objects that are
    values of this object's parameters). Dependencies can either be on
    Parameter values, or on other metadata about the Parameter.

    Parameters
    ----------
    watch : bool, optional
        Whether to invoke the function/method when the dependency is updated,
        by default False
    on_init : bool, optional
        Whether to invoke the function/method when the instance is created,
        by default False

    """
    ...

