"""
This type stub file was generated by pyright.
"""

"""
Optional IPython extension for working with Parameters.

This extension offers extended but completely optional functionality
for IPython users.  From within IPython, it may be loaded using:

%load_ext param.ipython

This will register the %params line magic to allow easy inspection of
all the parameters defined on a parameterized class or object:

%params <parameterized class or object>

All parameters of the class or object will be listed in the IPython
pager together with all their corresponding attributes and
docstrings. Note that the class or object to be inspected must already
exist in the active namespace.
"""
WARN_MISFORMATTED_DOCSTRINGS = ...
red = ...
blue = ...
green = ...
cyan = ...
class ParamPager:
    """
    Callable class that displays information about the supplied
    Parameterized object or class in the IPython pager.
    """
    def __init__(self, metaclass=...) -> None:
        """
        If metaclass is set to True, the checks for Parameterized
        classes objects are disabled. This option is for use in
        ParameterizedMetaclass for automatic docstring generation.
        """
        ...
    
    def get_param_info(self, obj, include_super=...): # -> tuple[dict[Any, Any], dict[Any, Any] | Any, list[Any]]:
        """
        Get the parameter dictionary, the list of modifed parameters
        and the dictionary of parameter values. If include_super is
        True, parameters are also collected from the super classes.
        """
        ...
    
    def param_docstrings(self, info, max_col_len=..., only_changed=...): # -> LiteralString:
        """
        Build a string to that presents all of the parameter
        docstrings in a clean format (alternating red and blue for
        readability).
        """
        ...
    
    def sort_by_precedence(self, parameters): # -> list[Any | str]:
        """
        Sort the provided dictionary of parameters by their precedence value,
        preserving the original ordering for parameters with the
        same precedence.
        """
        ...
    
    def __call__(self, param_obj): # -> str | None:
        """
        Given a Parameterized object or class, display information
        about the parameters in the IPython pager.
        """
        ...
    


message = ...
_loaded = ...
def load_ipython_extension(ip, verbose=...): # -> None:
    @magics_class
    class ParamMagics(Magics):
        """
        Implements the %params line magic used to inspect the parameters
        of a parameterized class or object.
        """
        ...
    
    

class IPythonDisplay:
    """Reactive display handler that updates the output."""
    enabled = ...
    def __init__(self, reactive) -> None:
        ...
    
    def __call__(self): # -> None:
        ...
    


def ipython_async_executor(func): # -> None:
    ...

