"""
This type stub file was generated by pyright.
"""

"""
Classes used to support string serialization of Parameters and
Parameterized objects.
"""
class UnserializableException(Exception):
    ...


class UnsafeserializableException(Exception):
    ...


def JSONNullable(json_type): # -> dict[str, list[Any]]:
    """Express a JSON schema type as nullable to easily support Parameters that allow_None"""
    ...

class Serialization:
    """Base class used to implement different types of serialization."""
    @classmethod
    def schema(cls, pobj, subset=...):
        ...
    
    @classmethod
    def serialize_parameters(cls, pobj, subset=...):
        """
        Serialize the parameters on a Parameterized object into a
        single serialized object, e.g. a JSON string.
        """
        ...
    
    @classmethod
    def deserialize_parameters(cls, pobj, serialized, subset=...):
        """
        Deserialize a serialized object representing one or
        more Parameters into a dictionary of parameter values.
        """
        ...
    
    @classmethod
    def serialize_parameter_value(cls, pobj, pname):
        """Serialize a single parameter value."""
        ...
    
    @classmethod
    def deserialize_parameter_value(cls, pobj, pname, value):
        """Deserialize a single parameter value."""
        ...
    


class JSONSerialization(Serialization):
    """
    Class responsible for specifying JSON serialization, deserialization
    and JSON schemas for Parameters and Parameterized classes and
    objects.
    """
    unserializable_parameter_types = ...
    json_schema_literal_types = ...
    @classmethod
    def loads(cls, serialized): # -> Any:
        ...
    
    @classmethod
    def dumps(cls, obj): # -> str:
        ...
    
    @classmethod
    def schema(cls, pobj, safe=..., subset=...): # -> dict[Any, Any]:
        ...
    
    @classmethod
    def serialize_parameters(cls, pobj, subset=...): # -> str:
        ...
    
    @classmethod
    def deserialize_parameters(cls, pobj, serialization, subset=...): # -> dict[Any, Any]:
        ...
    
    @classmethod
    def param_schema(cls, ptype, p, safe=..., subset=...): # -> dict[str, list[Any]] | Any | dict[str, Any]:
        ...
    
    @classmethod
    def serialize_parameter_value(cls, pobj, pname): # -> str:
        ...
    
    @classmethod
    def deserialize_parameter_value(cls, pobj, pname, value):
        ...
    
    @classmethod
    def class__schema(cls, class_, safe=...): # -> dict[str, list[Any]] | dict[str, str] | dict[str, Any]:
        ...
    
    @classmethod
    def array_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def classselector_schema(cls, p, safe=...): # -> dict[str, list[Any]] | dict[str, str] | dict[str, Any]:
        ...
    
    @classmethod
    def dict_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def date_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def calendardate_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def tuple_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def number_schema(cls, p, safe=...):
        ...
    
    @classmethod
    def declare_numeric_bounds(cls, schema, bounds, inclusive_bounds):
        """Given an applicable numeric schema, augment with bounds information"""
        ...
    
    @classmethod
    def integer_schema(cls, p, safe=...):
        ...
    
    @classmethod
    def numerictuple_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def xycoordinates_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def range_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def list_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    
    @classmethod
    def objectselector_schema(cls, p, safe=...): # -> dict[str, list[dict[str, str]]] | dict[Any, Any]:
        ...
    
    @classmethod
    def selector_schema(cls, p, safe=...): # -> dict[str, list[dict[str, str]]] | dict[Any, Any]:
        ...
    
    @classmethod
    def listselector_schema(cls, p, safe=...): # -> dict[str, str] | dict[str, Any]:
        ...
    
    @classmethod
    def dataframe_schema(cls, p, safe=...): # -> dict[str, str]:
        ...
    


